# Site settings
title: Ruby on Richards Blog
email: team@rubyonrichards.com
description: > # this means to ignore newlines until "baseurl:"
  Your personal code mentor.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://rubyonrichards.com" # the base hostname & protocol for your site
twitter_username: rubyonrichards

# Build settings
markdown: kramdown
highlighter: rouge
