name: Ruby on Richards Blog
description: Your personal code mentor.
meta_description: "Learn how to code with the help of a mentor."

aboutPage: false

markdown: kramdown
highlighter: rouge

paginate: 5
baseurl: "/blog/"
domain_name: 'http://rubyonrichards.com/blog'
google_analytics: 'UA-80910236-1'
disqus: true
disqus_shortname: 'http-www-rubyonrichards-com'

# Details for the RSS feed generator
url:            'http://www.rubyonrichards.com/blog'
author:         'Ruby on Richards'
authorTwitter:  'rubyonrichards'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
